version: "3.2"
services:
  accounts:
    build:
      context: .
      dockerfile: ./packages/accounts/Dockerfile
    ports:
      - '5000:5000'

  business:
    build:
      context: .
      dockerfile: ./packages/business/Dockerfile
    ports:
      - '5001:5001'

  orders:
    build:
      context: .
      dockerfile: ./packages/orders/Dockerfile
    ports:
      - '5002:5002'
    restart: always
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  payments:
    build:
      context: .
      dockerfile: ./packages/payments/Dockerfile
    ports:
      - '5003:5003'
    restart: always
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  cards:
    build:
      context: .
      dockerfile: ./packages/cards/Dockerfile
    ports:
      - '5004:5004'
    restart: always
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
